Repository OCA/l10n-chile, pull requests merged in 2019-10, with the labels that each got.

#6 [ADD] l10n_cl_toponym
  .travis.yml
  l10n_cl_toponym/README.rst
  l10n_cl_toponym/__init__.py
  l10n_cl_toponym/__manifest__.py
  l10n_cl_toponym/data/res.city.xml
  l10n_cl_toponym/data/res.country.state.region.xml
  l10n_cl_toponym/data/res.country.state.xml
  l10n_cl_toponym/i18n/es.po
  l10n_cl_toponym/i18n/es_CL.po
  l10n_cl_toponym/models/__init__.py
  l10n_cl_toponym/models/res_city.py
  l10n_cl_toponym/models/res_company.py
  l10n_cl_toponym/models/res_partner.py
  l10n_cl_toponym/models/res_state.py
  l10n_cl_toponym/models/res_state_region.py
  l10n_cl_toponym/readme/CONTRIBUTORS.rst
  l10n_cl_toponym/readme/DESCRIPTION.rst
  l10n_cl_toponym/readme/USAGE.rst
  l10n_cl_toponym/security/ir.model.access.csv
  l10n_cl_toponym/security/res_groups.xml
  l10n_cl_toponym/static/description/icon.png
  l10n_cl_toponym/static/description/index.html
  l10n_cl_toponym/static/description/pic1.png
  l10n_cl_toponym/static/description/pic2.png
  l10n_cl_toponym/views/res_city.xml
  l10n_cl_toponym/views/res_company.xml
  l10n_cl_toponym/views/res_partner.xml
  l10n_cl_toponym/views/res_state_view.xml
Labels: enhancement, needs review

#7 [ADD] l10n_cl_chart_of_account
  .travis.yml
  README.md
  l10n_cl_chart_of_account/README.rst
  l10n_cl_chart_of_account/__init__.py
  l10n_cl_chart_of_account/__manifest__.py
  l10n_cl_chart_of_account/data/account_chart_template_data.xml
  l10n_cl_chart_of_account/data/account_journal.xml
  l10n_cl_chart_of_account/data/account_tax_data.xml
  l10n_cl_chart_of_account/data/l10n_cl_chart_of_account_data.xml
  l10n_cl_chart_of_account/models/__init__.py
  l10n_cl_chart_of_account/models/account_invoice.py
  l10n_cl_chart_of_account/models/account_tax.py
  l10n_cl_chart_of_account/readme/CONTRIBUTORS.rst
  l10n_cl_chart_of_account/readme/DESCRIPTION.rst
  l10n_cl_chart_of_account/readme/USAGE.rst
  l10n_cl_chart_of_account/static/description/icon.png
  l10n_cl_chart_of_account/views/account_tax.xml
Labels: enhancement, needs review

#12 [ADD] l10n_cl_currency_rate_sbif
  l10n_cl_currency_rate_sbif/README.rst
  l10n_cl_currency_rate_sbif/__init__.py
  l10n_cl_currency_rate_sbif/__manifest__.py
  l10n_cl_currency_rate_sbif/data/decimal_precision.xml
  l10n_cl_currency_rate_sbif/data/ir_config_parameter.xml
  l10n_cl_currency_rate_sbif/data/ir_cron.xml
  l10n_cl_currency_rate_sbif/data/res.currency.csv
  l10n_cl_currency_rate_sbif/models/__init__.py
  l10n_cl_currency_rate_sbif/models/res_currency.py
  l10n_cl_currency_rate_sbif/models/res_currency_rate.py
  l10n_cl_currency_rate_sbif/readme/CONFIGURE.rst
  l10n_cl_currency_rate_sbif/readme/CONTRIBUTORS.rst
  l10n_cl_currency_rate_sbif/readme/DESCRIPTION.rst
  l10n_cl_currency_rate_sbif/readme/HISTORY.rst
  l10n_cl_currency_rate_sbif/readme/INSTALL.rst
  l10n_cl_currency_rate_sbif/readme/ROADMAP.rst
  l10n_cl_currency_rate_sbif/readme/USAGE.rst
  l10n_cl_currency_rate_sbif/static/description/icon.png
  l10n_cl_currency_rate_sbif/static/description/index.html
  l10n_cl_currency_rate_sbif/views/update_button.xml
Labels: approved, enhancement, needs review

#13 [IMP] l10n_cl_electronic_invoicing: Documentation
  l10n_cl_electronic_invoicing/README.rst
  l10n_cl_electronic_invoicing/__manifest__.py
  l10n_cl_electronic_invoicing/models/account_invoice.py
  l10n_cl_electronic_invoicing/models/account_tax.py
  l10n_cl_electronic_invoicing/readme/CONFIGURE.rst
  l10n_cl_electronic_invoicing/readme/INSTALL.rst
  l10n_cl_electronic_invoicing/readme/USAGE.rst
  l10n_cl_electronic_invoicing/static/images/01-res.company.png
  l10n_cl_electronic_invoicing/static/images/02-res.company.png
  l10n_cl_electronic_invoicing/static/images/03-res.company.png
  l10n_cl_electronic_invoicing/static/images/04-res.company.png
  l10n_cl_electronic_invoicing/static/images/05-account.journal.png
  l10n_cl_electronic_invoicing/static/images/06-account.journal.png
  l10n_cl_electronic_invoicing/static/images/07-account.journal.png
  l10n_cl_electronic_invoicing/static/images/08-ir.sequence.png
  l10n_cl_electronic_invoicing/static/images/09-ir.sequence.png
  l10n_cl_electronic_invoicing/static/images/10-fetchmail.server.png
  l10n_cl_electronic_invoicing/static/images/11-res.config.settings.png
  l10n_cl_electronic_invoicing/static/images/12-res.company.png
  l10n_cl_electronic_invoicing/static/images/13-www.sii.cl.png
Labels: approved, enhancement, needs review

#17 [IMP] l10n_cl_toponym
  l10n_cl_electronic_invoicing/__manifest__.py
  l10n_cl_electronic_invoicing/models/res_company.py
  l10n_cl_electronic_invoicing/models/res_users.py
  l10n_cl_electronic_invoicing/views/res_users.xml
  l10n_cl_toponym/__manifest__.py
  l10n_cl_toponym/data/res_city.xml
  l10n_cl_toponym/data/res_country.xml
  l10n_cl_toponym/data/res_country_state.xml
  l10n_cl_toponym/data/res_country_state_region.xml
  l10n_cl_toponym/models/__init__.py
  l10n_cl_toponym/models/res_company.py
  l10n_cl_toponym/models/res_country.py
  l10n_cl_toponym/models/res_partner.py
  l10n_cl_toponym/readme/DESCRIPTION.rst
  l10n_cl_toponym/views/res_city.xml
  l10n_cl_toponym/views/res_company.xml
  l10n_cl_toponym/views/res_country.xml
  l10n_cl_toponym/views/res_country_state.xml
  l10n_cl_toponym/views/res_country_state_region.xml
Labels: enhancement, needs review

#18 [ADD] l10n_cl_sii_activity
  l10n_cl_electronic_invoicing/__manifest__.py
  l10n_cl_electronic_invoicing/data/res_country.xml
  l10n_cl_electronic_invoicing/models/__init__.py
  l10n_cl_electronic_invoicing/models/account_journal.py
  l10n_cl_electronic_invoicing/models/partner_activities.py
  l10n_cl_electronic_invoicing/models/res_company.py
  l10n_cl_electronic_invoicing/security/ir.model.access.csv
  l10n_cl_electronic_invoicing/views/partner_activities.xml
  l10n_cl_electronic_invoicing/views/res_company.xml
  l10n_cl_electronic_invoicing/views/res_country_view.xml
  l10n_cl_electronic_invoicing/views/res_partner.xml
  l10n_cl_sii_activity/README.rst
  l10n_cl_sii_activity/__init__.py
  l10n_cl_sii_activity/__manifest__.py
  l10n_cl_sii_activity/data/sii.activity.csv
  l10n_cl_sii_activity/i18n/es_CL.po
  l10n_cl_sii_activity/models/__init__.py
  l10n_cl_sii_activity/models/res_company.py
  l10n_cl_sii_activity/models/sii_activity.py
  l10n_cl_sii_activity/readme/CONTRIBUTORS.rst
  l10n_cl_sii_activity/readme/DESCRIPTION.rst
  l10n_cl_sii_activity/readme/USAGE.rst
  l10n_cl_sii_activity/security/ir.model.access.csv
  l10n_cl_sii_activity/static/description/icon.png
  l10n_cl_sii_activity/views/res_company.xml
  l10n_cl_sii_activity/views/sii_activity.xml
Labels: enhancement, needs review

#20 [FIX] Typo
  l10n_cl_electronic_invoicing/models/caf.py
Labels: bug

#30 [ADD] res_partner_email_etd
  res_partner_email_etd/README.rst
  res_partner_email_etd/__init__.py
  res_partner_email_etd/__manifest__.py
  res_partner_email_etd/i18n/es_CL.po
  res_partner_email_etd/models/__init__.py
  res_partner_email_etd/models/res_partner.py
  res_partner_email_etd/readme/CONTRIBUTORS.rst
  res_partner_email_etd/readme/DESCRIPTION.rst
  res_partner_email_etd/readme/USAGE.rst
  res_partner_email_etd/static/description/icon.png
  res_partner_email_etd/views/res_partner.xml
Labels: enhancement, needs review

#19 [ADD] connector_acp
  connector_acp/README.rst
  connector_acp/__init__.py
  connector_acp/__manifest__.py
  connector_acp/models/__init__.py
  connector_acp/models/backend_acp.py
  connector_acp/models/res_company.py
  connector_acp/models/res_company_document.py
  connector_acp/models/ssl_certificate.py
  connector_acp/readme/CONFIGURE.rst
  connector_acp/readme/CONTRIBUTORS.rst
  connector_acp/readme/DESCRIPTION.rst
  connector_acp/readme/USAGE.rst
  connector_acp/security/ir.model.access.csv
  connector_acp/static/description/icon.png
  connector_acp/views/backend_acp.xml
  connector_acp/views/res_company.xml
  connector_acp/views/ssl_certificate.xml
  oca_dependencies.txt
Labels: enhancement, needs review

#25 [ADD] l10n_cl_invoicing_policy
  l10n_cl_electronic_invoicing/__manifest__.py
  l10n_cl_electronic_invoicing/data/res_partner.xml
  l10n_cl_invoicing_policy/README.rst
  l10n_cl_invoicing_policy/__init__.py
  l10n_cl_invoicing_policy/__manifest__.py
  l10n_cl_invoicing_policy/i18n/es_CL.po
  l10n_cl_invoicing_policy/models/__init__.py
  l10n_cl_invoicing_policy/models/res_partner.py
  l10n_cl_invoicing_policy/readme/CONTRIBUTORS.rst
  l10n_cl_invoicing_policy/readme/DESCRIPTION.rst
  l10n_cl_invoicing_policy/readme/USAGE.rst
  l10n_cl_invoicing_policy/static/description/icon.png
  l10n_cl_invoicing_policy/views/res_partner.xml
Labels: enhancement, needs review

#31 [IMP] l10n_cl_sii_activity
  l10n_cl_sii_activity/__manifest__.py
  l10n_cl_sii_activity/models/__init__.py
  l10n_cl_sii_activity/models/res_partner.py
  l10n_cl_sii_activity/views/res_company.xml
  l10n_cl_sii_activity/views/res_partner.xml
Labels: enhancement, needs review

#32 [IMP] connector_acp
  connector_acp/__manifest__.py
  connector_acp/models/__init__.py
  connector_acp/models/ssl_signature.py
  connector_acp/security/ir.model.access.csv
  connector_acp/views/ssl_signature.xml
Labels: enhancement, needs review

#27 [ADD] l10n_cl_sii_folio
  l10n_cl_sii_folio/README.rst
  l10n_cl_sii_folio/__init__.py
  l10n_cl_sii_folio/__manifest__.py
  l10n_cl_sii_folio/i18n/es_CL.po
  l10n_cl_sii_folio/models/__init__.py
  l10n_cl_sii_folio/models/ir_sequence.py
  l10n_cl_sii_folio/models/ir_sequence_folio.py
  l10n_cl_sii_folio/readme/CONTRIBUTORS.rst
  l10n_cl_sii_folio/readme/DESCRIPTION.rst
  l10n_cl_sii_folio/readme/USAGE.rst
  l10n_cl_sii_folio/security/ir.model.access.csv
  l10n_cl_sii_folio/static/description/icon.png
  l10n_cl_sii_folio/views/ir_sequence.xml
  l10n_cl_sii_folio/views/ir_sequence_folio.xml
Labels: enhancement, needs review
