Repository OCA/l10n-chile, pull requests merged in 2019-11, with the labels that each got.

#35 [IMP] connector_acp
  connector_acp/__manifest__.py
  connector_acp/models/__init__.py
  connector_acp/models/backend_acp.py
  connector_acp/models/res_company.py
  connector_acp/models/res_company_document.py
  connector_acp/models/res_country.py
  connector_acp/models/res_ssl_mixin.py
  connector_acp/security/ir.model.access.csv
  connector_acp/views/res_country.xml
Labels: enhancement, needs review

#38 [IMP] connector_acp
  connector_acp/__manifest__.py
  connector_acp/models/__init__.py
  connector_acp/models/etd_certificate.py
  connector_acp/models/etd_document.py
  connector_acp/models/etd_mixin.py
  connector_acp/models/etd_signature.py
  connector_acp/models/res_company.py
  connector_acp/security/ir.model.access.csv
  connector_acp/views/etd_certificate.xml
  connector_acp/views/etd_signature.xml
  connector_acp/views/res_company.xml
Labels: enhancement, needs review

#36 [ADD] l10n_cl_sii
  l10n_cl_sii/README.rst
  l10n_cl_sii/__init__.py
  l10n_cl_sii/__manifest__.py
  l10n_cl_sii/readme/CONTRIBUTORS.rst
  l10n_cl_sii/readme/DESCRIPTION.rst
  l10n_cl_sii/readme/USAGE.rst
  l10n_cl_sii/static/description/icon.png
  l10n_cl_sii/views/menuitem.xml
Labels: enhancement, needs review

#37 [ADD] l10n_cl_sii_reference_account
  l10n_cl_sii_reference_account/README.rst
  l10n_cl_sii_reference_account/__init__.py
  l10n_cl_sii_reference_account/__manifest__.py
  l10n_cl_sii_reference_account/models/__init__.py
  l10n_cl_sii_reference_account/models/account_invoice.py
  l10n_cl_sii_reference_account/models/sii_reference.py
  l10n_cl_sii_reference_account/readme/CONTRIBUTORS.rst
  l10n_cl_sii_reference_account/readme/DESCRIPTION.rst
  l10n_cl_sii_reference_account/readme/USAGE.rst
  l10n_cl_sii_reference_account/static/description/icon.png
  l10n_cl_sii_reference_account/views/account_invoice.xml
  l10n_cl_sii_reference_account/views/sii_reference.xml
Labels: enhancement, needs review

#40 [IMP] l10n_cl_sii_reference
  l10n_cl_sii_reference/__manifest__.py
  l10n_cl_sii_reference/i18n/es_CL.po
  l10n_cl_sii_reference/models/__init__.py
  l10n_cl_sii_reference/models/account_invoice.py
  l10n_cl_sii_reference/models/sii_reference.py
  l10n_cl_sii_reference/security/ir.model.access.csv
  l10n_cl_sii_reference/views/account_invoice.xml
  l10n_cl_sii_reference/views/menuitem.xml
  l10n_cl_sii_reference/views/sii_reference.xml
Labels: enhancement, needs review

#39 [IMP] l10n_cl_sii_folio
  l10n_cl_sii_folio/__manifest__.py
Labels: enhancement, needs review

#33 [ADD] l10n_cl_etd
  l10n_cl_etd/README.rst
  l10n_cl_etd/__init__.py
  l10n_cl_etd/__manifest__.py
  l10n_cl_etd/data/backend.acp.csv
  l10n_cl_etd/data/res.country.csv
  l10n_cl_etd/i18n/es_CL.po
  l10n_cl_etd/models/__init__.py
  l10n_cl_etd/models/etd_mixin.py
  l10n_cl_etd/models/res_company.py
  l10n_cl_etd/readme/CONTRIBUTORS.rst
  l10n_cl_etd/readme/DESCRIPTION.rst
  l10n_cl_etd/readme/USAGE.rst
  l10n_cl_etd/static/description/icon.png
Labels: enhancement, needs review

#42 [UPD] Update l10n_cl_invoicing_policy.pot
  l10n_cl_invoicing_policy/i18n/es_CL.po
Labels: enhancement, needs review

#26 [ADD] l10n_cl_etd_account
  l10n_cl_etd_account/README.rst
  l10n_cl_etd_account/__init__.py
  l10n_cl_etd_account/__manifest__.py
  l10n_cl_etd_account/data/etd_document.xml
  l10n_cl_etd_account/data/xml/invoice.xml
  l10n_cl_etd_account/data/xml/ticket.xml
  l10n_cl_etd_account/data/xsd/DTE_v10.xsd
  l10n_cl_etd_account/data/xsd/EnvioBOLETA_v11.xsd
  l10n_cl_etd_account/data/xsd/EnvioDTE_v10.xsd
  l10n_cl_etd_account/data/xsd/SiiTypes_v10.xsd
  l10n_cl_etd_account/data/xsd/xmldsignature_v10.xsd
  l10n_cl_etd_account/i18n/es_CL.po
  l10n_cl_etd_account/models/__init__.py
  l10n_cl_etd_account/models/account_invoice.py
  l10n_cl_etd_account/models/etd_document.py
  l10n_cl_etd_account/readme/CONFIGURE.rst
  l10n_cl_etd_account/readme/CONTRIBUTORS.rst
  l10n_cl_etd_account/readme/DESCRIPTION.rst
  l10n_cl_etd_account/readme/USAGE.rst
  l10n_cl_etd_account/security/ir.model.access.csv
  l10n_cl_etd_account/static/description/icon.png
  l10n_cl_etd_account/views/account_invoice.xml
  requirements.txt
Labels: enhancement, needs review

#28 [ADD] l10n_cl_etd_stock
  l10n_cl_etd_stock/README.rst
  l10n_cl_etd_stock/__init__.py
  l10n_cl_etd_stock/__manifest__.py
  l10n_cl_etd_stock/data/etd_document.xml
  l10n_cl_etd_stock/i18n/es_CL.po
  l10n_cl_etd_stock/models/__init__.py
  l10n_cl_etd_stock/models/delivery_carrier.py
  l10n_cl_etd_stock/models/etd_document.py
  l10n_cl_etd_stock/models/stock_picking.py
  l10n_cl_etd_stock/readme/CONFIGURE.rst
  l10n_cl_etd_stock/readme/CONTRIBUTORS.rst
  l10n_cl_etd_stock/readme/DESCRIPTION.rst
  l10n_cl_etd_stock/readme/USAGE.rst
  l10n_cl_etd_stock/static/description/icon.png
  l10n_cl_etd_stock/static/xml/picking.xml
  l10n_cl_etd_stock/static/xsd/DTE_v10.xsd
  l10n_cl_etd_stock/views/delivery_carrier.xml
  l10n_cl_etd_stock/views/stock_picking.xml
Labels: enhancement, needs review

#41 [FIX] Various small fixes and improvements
  connector_acp/models/etd_mixin.py
  l10n_cl_sii/readme/CONTRIBUTORS.rst
  l10n_cl_sii/readme/DESCRIPTION.rst
  l10n_cl_sii/readme/USAGE.rst
  l10n_cl_sii_reference_account/readme/CONTRIBUTORS.rst
  l10n_cl_sii_reference_account/readme/DESCRIPTION.rst
  l10n_cl_sii_reference_account/readme/USAGE.rst
Labels: bug, enhancement, needs review

#29 [ADD] connector_acp_xerox
  connector_acp_xerox/__init__.py
  connector_acp_xerox/__manifest__.py
  connector_acp_xerox/data/backend.acp.csv
  connector_acp_xerox/models/__init__.py
  connector_acp_xerox/models/backend_acp.py
  connector_acp_xerox/readme/CONFIGURE.rst
  connector_acp_xerox/readme/CONTRIBUTORS.rst
  connector_acp_xerox/readme/DESCRIPTION.rst
  connector_acp_xerox/readme/USAGE.rst
  connector_acp_xerox/static/description/icon.png
Labels: enhancement, needs review

#43 [IMP] Repo Addons Table
  README.md
Labels: enhancement
