Repository OCA/l10n-chile, pull requests merged in 2020-02, with the labels that each got.

#75 [ADD] connector_acp_ftp: add FTP backend support
  connector_acp_ftp/README.rst
  connector_acp_ftp/__init__.py
  connector_acp_ftp/__manifest__.py
  connector_acp_ftp/models/__init__.py
  connector_acp_ftp/models/backend_acp.py
  connector_acp_ftp/readme/CONTRIBUTORS.rst
  connector_acp_ftp/readme/DESCRIPTION.rst
  connector_acp_ftp/readme/USAGE.rst
  connector_acp_ftp/static/description/icon.png
  connector_acp_ftp/static/description/index.html
Labels: enhancement, needs review

#82 [FIX] connector_acp_ftp: Change to confirmed on successful connection test
  connector_acp_ftp/models/backend_acp.py
Labels: approved, bug, needs review

#84 [IMP] l10n_cl_etd_xerox: Only sign records with DTE class
  l10n_cl_etd_xerox/models/etd_document.py
Labels: approved, enhancement, needs review

#83 [FIX] connector_acp
  connector_acp/models/etd_mixin.py
Labels: approved, bug, needs review

#85 [FIX] l10n_cl_etd_xerox: SII Activity correct mapping
  l10n_cl_etd_xerox/data/etd_document_invoice.xml
  l10n_cl_etd_xerox/data/etd_document_stock.xml
Labels: approved, bug, needs review

#86 [IMP] connector_acp: Reset status
  connector_acp/models/backend_acp.py
Labels: approved, enhancement, needs review

#78 [ADD] l10n_etd_xerox_fsmroute: Xerox ETD for FSM Day Routes
  l10n_cl_etd_xerox_fsmroute/README.rst
  l10n_cl_etd_xerox_fsmroute/__init__.py
  l10n_cl_etd_xerox_fsmroute/__manifest__.py
  l10n_cl_etd_xerox_fsmroute/models/__init__.py
  l10n_cl_etd_xerox_fsmroute/models/etd_mixin.py
  l10n_cl_etd_xerox_fsmroute/models/fsm_route.py
  l10n_cl_etd_xerox_fsmroute/readme/CONTRIBUTORS.rst
  l10n_cl_etd_xerox_fsmroute/readme/DESCRIPTION.rst
  l10n_cl_etd_xerox_fsmroute/static/description/icon.png
  l10n_cl_etd_xerox_fsmroute/static/description/index.html
  oca_dependencies.txt
Labels: approved, enhancement, needs review
