Repository OCA/l10n-chile, pull requests merged in 2020-05, with the labels that each got.

#101 [FIX] l10n_cl_chart_of_account: AttributeError: 'account.invoice.tax'…
  l10n_cl_chart_of_account/models/__init__.py
  l10n_cl_chart_of_account/models/account_invoice.py
  l10n_cl_chart_of_account/models/account_invoice_tax.py
Labels: approved, bot is merging ⏳, bug, needs review

#104 [FIX] l10n_cl_etd
  l10n_cl_etd/models/etd_mixin.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#102 [IMP] l10n_cl_etd_stock: Allow signing batch picking
  l10n_cl_etd_stock/__manifest__.py
  l10n_cl_etd_stock/models/__init__.py
  l10n_cl_etd_stock/models/stock_picking_batch.py
  l10n_cl_etd_stock/views/stock_picking_batch.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#103 [IMP] l10n_cl_etd_account: Set the correct SII document when refunding
  l10n_cl_etd_account/__init__.py
  l10n_cl_etd_account/models/account_invoice.py
  l10n_cl_etd_account/wizard/__init__.py
  l10n_cl_etd_account/wizard/account_invoice_refund.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#105 [IMP] l10n_cl_sii_reference_account
  l10n_cl_sii_reference_account/models/account_invoice.py
  l10n_cl_sii_reference_account/models/sii_reference.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#107 [FIX] l10n_cl_toponym: RUT k -> K
  l10n_cl_toponym/models/res_partner.py
Labels: approved, bot is merging ⏳, bug, needs review

#108 [FIX] connector_dicom
  connector_dicom/models/res_partner.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge
