Repository OCA/l10n-chile, pull requests merged in 2020-04, with the labels that each got.

#77 [ADD] connector_dicom
  connector_dicom/README.rst
  connector_dicom/__init__.py
  connector_dicom/__manifest__.py
  connector_dicom/data/ir_config_parameter.xml
  connector_dicom/i18n/es_CL.po
  connector_dicom/models/__init__.py
  connector_dicom/models/res_partner.py
  connector_dicom/models/res_partner_dicom.py
  connector_dicom/readme/CONFIGURE.rst
  connector_dicom/readme/CONTRIBUTORS.rst
  connector_dicom/readme/DESCRIPTION.rst
  connector_dicom/readme/USAGE.rst
  connector_dicom/security/ir.model.access.csv
  connector_dicom/static/description/icon.png
  connector_dicom/views/res_partner.xml
  connector_dicom/views/res_partner_dicom.xml
Labels: bot is merging ⏳, enhancement, needs review

#89 [FIX] l10n_cl_sii_folio: Reference to the Sequence class_id field
  l10n_cl_sii_folio/models/ir_sequence_folio.py
Labels: approved, bot is merging ⏳, bug, needs review

#91 [ADD] connector_dicom_crm
  .gitignore
  connector_dicom_crm/README.rst
  connector_dicom_crm/__init__.py
  connector_dicom_crm/__manifest__.py
  connector_dicom_crm/i18n/es_CL.po
  connector_dicom_crm/models/__init__.py
  connector_dicom_crm/models/crm_lead.py
  connector_dicom_crm/readme/CONTRIBUTORS.rst
  connector_dicom_crm/readme/DESCRIPTION.rst
  connector_dicom_crm/readme/USAGE.rst
  connector_dicom_crm/static/description/icon.png
  connector_dicom_crm/views/crm_lead_views.xml
Labels: bot is merging ⏳, enhancement, needs review

#93 [FIX] l10n_cl_sii_folio: Folio validation accept format 99999999-9
  l10n_cl_sii_folio/models/ir_sequence_folio.py
Labels: approved, bot is merging ⏳, bug, needs review

#94 [IMP] Connector ACP: allow to Check confirmed connections
  connector_acp/views/backend_acp.xml
Labels: enhancement, needs review

#87 [ADD] l10n_cl_etd_xerox_fsmroute: Day Route Xerox Tipo 1 documents
  connector_acp/models/etd_mixin.py
  connector_acp/views/backend_acp.xml
  l10n_cl_etd_xerox/models/etd_document.py
  l10n_cl_etd_xerox_fsmroute/__manifest__.py
  l10n_cl_etd_xerox_fsmroute/data/etd_document_route_01.xml
  l10n_cl_etd_xerox_fsmroute/data/etd_document_route_05.xml
  l10n_cl_etd_xerox_fsmroute/data/etd_document_route_07.xml
  l10n_cl_etd_xerox_fsmroute/data/etd_document_route_11.xml
  l10n_cl_etd_xerox_fsmroute/models/__init__.py
  l10n_cl_etd_xerox_fsmroute/models/etd_document.py
  l10n_cl_etd_xerox_fsmroute/models/etd_mixin.py
  l10n_cl_etd_xerox_fsmroute/models/fsm_route.py
  l10n_cl_etd_xerox_fsmroute/models/fsm_route_dayroute.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#95 [FIX] l10n_cl_invoicing_policy
  l10n_cl_invoicing_policy/models/res_partner.py
Labels: approved, bot is merging ⏳, bug, needs review
