Repository OCA/l10n-chile, pull requests merged in 2020-01, with the labels that each got.

#62 [IMP] l10n_cl_invoicing_policy
  l10n_cl_invoicing_policy/models/res_partner.py
Labels: enhancement, needs review

#65 [FIX] l10n_cl_toponym
  l10n_cl_toponym/models/res_partner.py
Labels: approved, bug, needs review

#66 [IMP] l10n_cl_sii_activity
  l10n_cl_sii_activity/models/res_partner.py
  l10n_cl_sii_activity/views/res_partner.xml
Labels: approved, enhancement, needs review

#70 [FIX] TypeError: object of type 'bool' has no len()
  l10n_cl_toponym/models/res_partner.py
  l10n_cl_toponym/readme/CONTRIBUTORS.rst
Labels: approved, bug, needs review

#74 [FIX] l10n_cl_toponym
  l10n_cl_toponym/models/res_partner.py
Labels: approved, bug, needs review
